Import pandas and numpy for the libraries

In [1]:
import pandas as pd
import numpy as np

Read the dataset 'citibike.csv'

In [11]:
df=pd.read_csv('citibike.csv')

Show the head (the first 5 rows of the dataset)

In [13]:
df.head()

Start Time       Stop Time  Start Station ID Start Station Name  \
0  01-01-17 00:38    1-1-17 01:03              3194    McGinley Square   
1  01-01-17 01:47  01-01-17 01:58              3183     Exchange Place   
2  01-01-17 01:47  01-01-17 01:58              3183     Exchange Place   
3  01-01-17 01:56  01-01-17 02:00              3186      Grove St PATH   
4    1-1-17 02:12  01-01-17 02:23              3270    Jersey & 6th St   

   End Station ID     End Station Name  Bike ID   User Type  Birth Year  Age  \
0            3271  Danforth Light Rail    24668  Subscriber        1961   60   
1            3203        Hamilton Park    26167  Subscriber        1993   28   
2            3203        Hamilton Park    26167  Subscriber        1993   28   
3            3270      Jersey & 6th St    24604  Subscriber        1970   51   
4            3206              Hilltop    24641  Subscriber        1978   43   

  Age Groups  Trip Duration Trip_Duration_in_min  Month  Season  Temperature  \
0      55-64           1513                   25      1  Winter           10   
1      25-34            639                   11      1  Winter           10   
2      25-34            639                   11      1  Winter           10   
3      45-54            258                    4      1  Winter           10   
4      35-44            663                   11      1  Winter           10   

  Weekday  
0  Sunday  
1  Sunday  
2  Sunday  
3  Sunday  
4  Sunday

Show the tail (the last 5 rows of the dataset)

In [14]:
df.tail()

Start Time       Stop Time  Start Station ID Start Station Name  \
20395  31-03-17 21:06  31-03-17 21:10              3186      Grove St PATH   
20396  31-03-17 21:13   31-3-17 21:18              3195            Sip Ave   
20397  31-03-17 21:13   31-3-17 21:18              3195            Sip Ave   
20398  31-03-17 21:26  31-03-17 21:30              3195            Sip Ave   
20399   31-3-17 23:20  31-03-17 23:30              3272       Jersey & 3rd   

       End Station ID End Station Name  Bike ID   User Type  Birth Year  Age  \
20395            3203    Hamilton Park    24608  Subscriber        1968   53   
20396            3194  McGinley Square    29219  Subscriber        1956   65   
20397            3194  McGinley Square    29219  Subscriber        1956   65   
20398            3201           Dey St    29276  Subscriber        1970   51   
20399            3268   Lafayette Park    24398  Subscriber        1984   37   

      Age Groups  Trip Duration Trip_Duration_in_min  Month  Season  \
20395      45-54            244                    4      3  Spring   
20396      65-74            264                    4      3  Spring   
20397      65-74            264                    4      3  Spring   
20398      45-54            239                    4      3  Spring   
20399      35-44            618                   10      3  Spring   

       Temperature Weekday  
20395           18  Friday  
20396           18  Friday  
20397           18  Friday  
20398           18  Friday  
20399           18  Friday

Show the info of all the columns

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20400 entries, 0 to 20399
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Start Time            20400 non-null  object
 1   Stop Time             20400 non-null  object
 2   Start Station ID      20400 non-null  int64 
 3   Start Station Name    20400 non-null  object
 4   End Station ID        20400 non-null  int64 
 5   End Station Name      20399 non-null  object
 6   Bike ID               20400 non-null  int64 
 7   User Type             20400 non-null  object
 8   Birth Year            20400 non-null  int64 
 9   Age                   20400 non-null  int64 
 10  Age Groups            20400 non-null  object
 11  Trip Duration         20400 non-null  int64 
 12  Trip_Duration_in_min  20400 non-null  object
 13  Month                 20400 non-null  int64 
 14  Season                20400 non-null  object
 15  Temperature           20400 non-null

Show the null

In [24]:
nan_in_col  = df[df['End Station Name'].isna()]

In [25]:
print(nan_in_col)

          Start Time      Stop Time  Start Station ID Start Station Name  \
9858  25-02-17 12:36  25-2-17 12:44              3220  5 Corners Library   

      End Station ID End Station Name  Bike ID   User Type  Birth Year  Age  \
9858            3211              NaN    24522  Subscriber        1963   58   

     Age Groups  Trip Duration Trip_Duration_in_min  Month  Season  \
9858      55-64            532                    9      2  Winter   

      Temperature   Weekday  
9858           11  Saturday  


Show only rows where 'End Station ID' is 3211

In [26]:
df.loc[df['End Station ID'] == 3211]

Start Time       Stop Time  Start Station ID Start Station Name  \
10     01-01-17 06:29    1-1-17 06:31              3186      Grove St PATH   
11     01-01-17 06:29  01-01-17 06:31              3186      Grove St PATH   
13     01-01-17 08:24    1-1-17 08:28              3186      Grove St PATH   
129    02-01-17 11:52    2-1-17 11:55              3203      Hamilton Park   
131      2-1-17 12:53  02-01-17 12:57              3269    Brunswick & 6th   
...               ...             ...               ...                ...   
20056   30-3-17 17:04  30-03-17 17:09              3275     Columbus Drive   
20110   30-3-17 18:00  30-03-17 18:02              3209       Brunswick St   
20230  30-03-17 20:54   30-3-17 20:57              3209       Brunswick St   
20231  30-03-17 20:54  30-03-17 20:57              3209       Brunswick St   
20362  31-03-17 16:56  31-03-17 16:58              3270    Jersey & 6th St   

       End Station ID End Station Name  Bike ID   User Type  Birth Year  Age  \
10               3211       Newark Ave    24681  Subscriber        1964   57   
11               3211       Newark Ave    24681  Subscriber        1964   57   
13               3211       Newark Ave    26308  Subscriber        1977   44   
129              3211       Newark Ave    26270  Subscriber        1974   47   
131              3211       Newark Ave    24675  Subscriber        1976   45   
...               ...              ...      ...         ...         ...  ...   
20056            3211       Newark Ave    24499  Subscriber        1982   39   
20110            3211       Newark Ave    24455  Subscriber        1975   46   
20230            3211       Newark Ave    29212  Subscriber        1984   37   
20231            3211       Newark Ave    26217  Subscriber        1989   32   
20362            3211       Newark Ave    26265  Subscriber        1971   50   

      Age Groups  Trip Duration Trip_Duration_in_min  Month  Season  \
10         55-64            107                    2      1  Winter   
11         55-64            107                    2      1  Winter   
13         35-44            258                    4      1  Winter   
129        45-54            199                    3      1  Winter   
131        45-54            238                    4      1  Winter   
...          ...            ...                  ...    ...     ...   
20056      35-44            312                    5      3  Spring   
20110      45-54            132                    2      3  Spring   
20230      35-44            162                    3      3  Spring   
20231      25-34            171                    3      3  Spring   
20362      45-54             99                    2      3  Spring   

       Temperature   Weekday  
10              10    Sunday  
11              10    Sunday  
13              10    Sunday  
129             12    Monday  
131             12    Monday  
...            ...       ...  
20056           18  Thursday  
20110           18  Thursday  
20230           18  Thursday  
20231           18  Thursday  
20362           18    Friday  

[626 rows x 17 columns]

Insert value 'Newark Ave' to the missing value of 'End Station Name' which index is 9858

In [32]:
df.at[9858, 'End Station Name'] = 'Newark Ave'

Check if the value has already been added

In [33]:
df.loc[9858,'End Station Name']

'Newark Ave'

Show the info to see if the NaN or null value is already filled

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20400 entries, 0 to 20399
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Start Time            20400 non-null  object
 1   Stop Time             20400 non-null  object
 2   Start Station ID      20400 non-null  int64 
 3   Start Station Name    20400 non-null  object
 4   End Station ID        20400 non-null  int64 
 5   End Station Name      20400 non-null  object
 6   Bike ID               20400 non-null  int64 
 7   User Type             20400 non-null  object
 8   Birth Year            20400 non-null  int64 
 9   Age                   20400 non-null  int64 
 10  Age Groups            20400 non-null  object
 11  Trip Duration         20400 non-null  int64 
 12  Trip_Duration_in_min  20400 non-null  object
 13  Month                 20400 non-null  int64 
 14  Season                20400 non-null  object
 15  Temperature           20400 non-null

Remove duplicates

In [35]:
df.drop_duplicates()

Start Time       Stop Time  Start Station ID Start Station Name  \
0      01-01-17 00:38    1-1-17 01:03              3194    McGinley Square   
1      01-01-17 01:47  01-01-17 01:58              3183     Exchange Place   
3      01-01-17 01:56  01-01-17 02:00              3186      Grove St PATH   
4        1-1-17 02:12  01-01-17 02:23              3270    Jersey & 6th St   
5      01-01-17 02:22    1-1-17 02:31              3212    Christ Hospital   
...               ...             ...               ...                ...   
20393   31-3-17 21:03   31-3-17 21:12              3278   Monmouth and 6th   
20394  31-03-17 21:06  31-03-17 21:10              3186      Grove St PATH   
20396  31-03-17 21:13   31-3-17 21:18              3195            Sip Ave   
20398  31-03-17 21:26  31-03-17 21:30              3195            Sip Ave   
20399   31-3-17 23:20  31-03-17 23:30              3272       Jersey & 3rd   

       End Station ID       End Station Name  Bike ID   User Type  Birth Year  \
0                3271    Danforth Light Rail    24668  Subscriber        1961   
1                3203          Hamilton Park    26167  Subscriber        1993   
3                3270        Jersey & 6th St    24604  Subscriber        1970   
4                3206                Hilltop    24641  Subscriber        1978   
5                3225  Baldwin at Montgomery    24520  Subscriber        1987   
...               ...                    ...      ...         ...         ...   
20393            3278       Monmouth and 6th    26221  Subscriber        1958   
20394            3203          Hamilton Park    24608  Subscriber        1968   
20396            3194        McGinley Square    29219  Subscriber        1956   
20398            3201                 Dey St    29276  Subscriber        1970   
20399            3268         Lafayette Park    24398  Subscriber        1984   

       Age Age Groups  Trip Duration Trip_Duration_in_min  Month  Season  \
0       60      55-64           1513                   25      1  Winter   
1       28      25-34            639                   11      1  Winter   
3       51      45-54            258                    4      1  Winter   
4       43      35-44            663                   11      1  Winter   
5       34      25-34            535                    9      1  Winter   
...    ...        ...            ...                  ...    ...     ...   
20393   63      55-64            577                   10      3  Spring   
20394   53      45-54            244                    4      3  Spring   
20396   65      65-74            264                    4      3  Spring   
20398   51      45-54            239                    4      3  Spring   
20399   37      35-44            618                   10      3  Spring   

       Temperature Weekday  
0               10  Sunday  
1               10  Sunday  
3               10  Sunday  
4               10  Sunday  
5               10  Sunday  
...            ...     ...  
20393           18  Friday  
20394           18  Friday  
20396           18  Friday  
20398           18  Friday  
20399           18  Friday  

[18449 rows x 17 columns]